"""Emit the per-hardware decision grid (CSV + Markdown) from a web payload.

Wave 30 (Jul 2026): this emitter was previously run ad hoc and never
checked in — the shipped decision-grid-h100.{csv,md} said "Generated by
scripts/_generator_payload.py" but no code in the repo could reproduce
them. It now lives here, reads the payload's `cells` field (which
_build_family_rollup ranks with the optimizer's canonical display sort
key as of Wave 30), and renders:

  decision-grid-<hw>.csv   one row per (params, tokens, ctx) cell
  decision-grid-<hw>.md    tokens=2T winner table, params x ctx

Usage:
  python3 scripts/emit_decision_grid.py PAYLOAD.json OUT_DIR [--hw h100]

Optionally rebuilds the rollup/smoothing/plateau chain in place first
(--rebuild), which is how a fixed picker propagates into an existing
payload without re-running the optimizer searches.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
for _p in (os.path.join(_ROOT, "ac"), _ROOT, _HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

PARAM_ORDER = [1.0, 3.0, 7.0, 13.0, 120.0, 500.0, 750.0, 1000.0]
TOKEN_ORDER = [0.5, 2.0, 10.0, 20.0]
CTX_ORDER = [8192, 32768, 131072, 1048576, 2097152, 4194304]

CSV_HEADER = (
    "params_B,tokens_T,context,winner,winner_loss,winner_tbt_ms,"
    "winner_ttft_ms,winner_mem_gb,winner_tp,spill_tier,runner_up,"
    "runner_loss_delta_pct,runner_tbt_delta_pct,plateau_with"
)


def _compact_family_name(arch_mode, state_type=None) -> str:
    """`moe_hybrid(mamba2)` / `hybrid(sliding_window)` / `dense` — the
    compact spelling used in the plateau column and md `≈` marker."""
    if state_type:
        return f"{arch_mode}({state_type})"
    return str(arch_mode)


def _plateau_str(fam: dict) -> str:
    p = fam.get("plateau_with")
    if not isinstance(p, dict):
        return ""
    return _compact_family_name(p.get("arch_mode"), p.get("state_type"))


def _cell_key(cell):
    return (cell.get("params_B"), cell.get("tokens_T"),
            cell.get("context_length"))


def rebuild_chain(data: dict) -> dict:
    """Re-run the post-search pipeline (rollup → smoothing → pin →
    plateau) on an existing payload. No optimizer searches are re-run;
    the grid rows' serialized optimal/pareto records are the input.
    Wave 31: delegates to the generator's canonical run_post_chain so
    the two entry points can never drift."""
    import _generator_payload as gp
    return gp.run_post_chain(data)


def emit(data: dict, out_dir: str, hw: str) -> None:
    cells = [c for c in data.get("cells", []) if c.get("hw") == hw]
    by_key = {_cell_key(c): c for c in cells}
    ctx_labels = {c.get("context_length"): c.get("context_label")
                  for c in cells}

    # ---- CSV ----------------------------------------------------------
    lines = [CSV_HEADER]
    for p in PARAM_ORDER:
        for t in TOKEN_ORDER:
            for ctx in CTX_ORDER:
                cell = by_key.get((p, t, ctx))
                if not cell or not cell.get("families"):
                    continue
                fams = cell["families"]
                w = fams[0]
                runner = fams[1] if len(fams) > 1 else {}
                lines.append(",".join(str(x) for x in [
                    p, t, ctx_labels.get(ctx, ctx),
                    w.get("display", ""),
                    round(float(w.get("loss") or 0.0), 4),
                    round(float(w.get("tbt_ms") or 0.0), 1),
                    int(round(float(w.get("ttft_ms") or 0.0))),
                    round(float(w.get("mem_gb") or 0.0), 1),
                    w.get("tp", ""),
                    w.get("spill_tier", "fits"),
                    runner.get("display", ""),
                    runner.get("loss_delta_pct", ""),
                    runner.get("tbt_delta_pct", ""),
                    _plateau_str(w),
                ]))
    csv_path = os.path.join(out_dir, f"decision-grid-{hw}.csv")
    with open(csv_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {csv_path} ({len(lines) - 1} rows)")

    # ---- Markdown (headline table at the payload's anchor token count) --
    # Wave 44 fix: the headline table hardcoded tokens=2.0; a payload
    # regenerated at a single different token count (e.g. 20T) rendered an
    # all-dashes table. Use the largest token count actually present.
    _tokens_present = sorted({k[1] for k in by_key})
    headline_tokens = _tokens_present[-1] if _tokens_present else 2.0
    md = [
        f"# {hw.upper()} decision grid — winner per cell",
        "",
        "Generated by ac-cli-release scripts/emit_decision_grid.py from the "
        "multi-ctx web payload. Family representatives AND the cross-family "
        "cell winner are ranked by the optimizer's canonical "
        "uncertainty-aware sort key (loss noise-band bucket, then "
        "memory/TBT/-TPS — Wave 30): loss stays strictly dominant outside "
        "the noise band, and inside it spilled or throughput-degenerate "
        "records no longer win on sub-noise loss edges. \"≈\" marks a "
        "plateau tie within the uncertainty band.",
        "",
        f"## tokens = {headline_tokens:g}T",
        "",
        "| params \\ ctx | " + " | ".join(
            ctx_labels.get(c, str(c)) for c in CTX_ORDER) + " |",
        "|---" * (len(CTX_ORDER) + 1) + "|",
    ]
    for p in PARAM_ORDER:
        row = [f"**{p:g}B**"]
        for ctx in CTX_ORDER:
            cell = by_key.get((p, headline_tokens, ctx))
            if not cell or not cell.get("families"):
                row.append("—")
                continue
            w = cell["families"][0]
            name = w.get("display", "?")
            plateau = _plateau_str(w)
            if plateau:
                name = f"{name} ≈{plateau}"
            row.append(
                f"{name}<br>L={float(w.get('loss') or 0):.3f}, "
                f"TBT={int(round(float(w.get('tbt_ms') or 0)))}ms")
        md.append("| " + " | ".join(row) + " |")
    md_path = os.path.join(out_dir, f"decision-grid-{hw}.md")
    with open(md_path, "w") as f:
        f.write("\n".join(md) + "\n")
    print(f"Wrote {md_path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("payload")
    ap.add_argument("out_dir")
    ap.add_argument("--hw", default="h100")
    ap.add_argument("--rebuild", action="store_true",
                    help="re-run rollup/smoothing/plateau on the payload "
                         "and write it back before emitting the grid")
    args = ap.parse_args()

    with open(args.payload) as f:
        data = json.load(f)
    if args.rebuild:
        data = rebuild_chain(data)
        with open(args.payload, "w") as f:
            json.dump(data, f, separators=(",", ":"))
        print(f"Rebuilt rollup chain and rewrote {args.payload}")
    emit(data, args.out_dir, args.hw)


if __name__ == "__main__":
    main()
