"""
Generate reference PyTorch implementations from AC schema configs.

The generated module is intentionally dependency-light at generation time and
dependency-explicit at runtime. It uses PyTorch for ordinary dense pieces, tries
FlashAttention for attention when available, and exposes component override
hooks for lab-local FLA/Mamba/NSA kernels.
"""

from __future__ import annotations

import json
import keyword
from pathlib import Path
from typing import Any, Dict, Optional


def _validate_class_name(name: str) -> str:
    if not name or not name.isidentifier() or keyword.iskeyword(name):
        raise ValueError(f"Invalid Python class name: {name!r}")
    return name


def generate_pytorch_implementation(
    config: Dict[str, Any],
    *,
    class_name: str = "ACGeneratedModel",
    source_name: Optional[str] = None,
) -> str:
    """Return a standalone PyTorch implementation module for an AC config."""

    class_name = _validate_class_name(class_name)
    config_json = json.dumps(config, indent=2, sort_keys=True)
    if "'''" in config_json:
        config_literal = repr(config_json)
    else:
        config_literal = "r'''\n" + config_json + "\n'''"
    source_comment = source_name or "AC generated architecture config"
    template = _PYTORCH_TEMPLATE
    return (
        template
        .replace("__CLASS_NAME__", class_name)
        .replace("__CONFIG_JSON_LITERAL__", config_literal)
        .replace("__SOURCE_COMMENT__", source_comment.replace("\n", " "))
    )


def save_pytorch_implementation(
    config: Dict[str, Any],
    path: str,
    *,
    class_name: str = "ACGeneratedModel",
    source_name: Optional[str] = None,
) -> None:
    """Write a standalone PyTorch implementation module to `path`."""

    out = Path(path)
    if out.parent and str(out.parent) != ".":
        out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        generate_pytorch_implementation(
            config, class_name=class_name, source_name=source_name),
        encoding="utf-8",
    )


_PYTORCH_TEMPLATE = '''# Generated by AC Architecture Compiler.
# Source: __SOURCE_COMMENT__
#
# This is a reference implementation scaffold, not a production training stack.
# It composes the architecture specified by AC_CONFIG and provides hooks for
# lab-local kernels such as flash-attn, FLA, Mamba, or custom NSA modules.

from __future__ import annotations

import importlib
import json
import math
from typing import Any, Callable, Dict, List, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


AC_CONFIG: Dict[str, Any] = json.loads(__CONFIG_JSON_LITERAL__)


def _optional_attr(module_name: str, attr_name: str):
    try:
        module = importlib.import_module(module_name)
    except Exception:
        return None
    return getattr(module, attr_name, None)


def _precision_to_dtype(name: str):
    key = str(name or "bf16").lower()
    if key in {"fp16", "float16"}:
        return torch.float16
    if key in {"fp32", "float32"}:
        return torch.float32
    # FP8/FP4/MX formats need stack-specific modules. The reference path keeps
    # parameters in BF16 and leaves real quantized kernels to overrides.
    return torch.bfloat16


class ACRMSNorm(nn.Module):
    def __init__(self, d_model: int, eps: float = 1e-5):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(d_model))
        self.eps = eps

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        variance = x.float().pow(2).mean(dim=-1, keepdim=True)
        out = x * torch.rsqrt(variance + self.eps).to(dtype=x.dtype)
        return out * self.weight.to(dtype=x.dtype)


def _rotate_half(x: torch.Tensor) -> torch.Tensor:
    x1 = x[..., ::2]
    x2 = x[..., 1::2]
    out = torch.stack((-x2, x1), dim=-1)
    return out.flatten(-2)


def _apply_rope(x: torch.Tensor, base: float = 500000.0) -> torch.Tensor:
    # x: [batch, heads, seq, head_dim]
    head_dim = x.shape[-1]
    rotary_dim = (head_dim // 2) * 2
    if rotary_dim == 0:
        return x
    seq = x.shape[-2]
    device = x.device
    dtype = x.dtype
    inv_freq = 1.0 / (base ** (torch.arange(0, rotary_dim, 2, device=device).float() / rotary_dim))
    t = torch.arange(seq, device=device).float()
    freqs = torch.einsum("s,d->sd", t, inv_freq)
    cos = freqs.cos()[None, None, :, :].repeat_interleave(2, dim=-1).to(dtype=dtype)
    sin = freqs.sin()[None, None, :, :].repeat_interleave(2, dim=-1).to(dtype=dtype)
    x_rope = x[..., :rotary_dim]
    x_pass = x[..., rotary_dim:]
    return torch.cat((x_rope * cos + _rotate_half(x_rope) * sin, x_pass), dim=-1)


class ACSwiGLUFFN(nn.Module):
    def __init__(self, d_model: int, ffn_dim: int, precision: str = "bf16"):
        super().__init__()
        dtype = _precision_to_dtype(precision)
        self.up = nn.Linear(d_model, ffn_dim, bias=False, dtype=dtype)
        self.gate = nn.Linear(d_model, ffn_dim, bias=False, dtype=dtype)
        self.down = nn.Linear(ffn_dim, d_model, bias=False, dtype=dtype)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.down(F.silu(self.gate(x)) * self.up(x))


class ACMoEFFN(nn.Module):
    def __init__(self, d_model: int, cfg: Dict[str, Any]):
        super().__init__()
        self.n_experts = int(cfg["n_experts"])
        self.top_k = int(cfg.get("top_k", 1))
        expert_dim = int(cfg["expert_dim"])
        precision = str(cfg.get("precision", "bf16"))
        router_cfg = cfg.get("router") or {}
        router_dtype = _precision_to_dtype(router_cfg.get("precision", "bf16"))
        self.router = nn.Linear(d_model, self.n_experts, bias=False, dtype=router_dtype)
        self.experts = nn.ModuleList([
            ACSwiGLUFFN(d_model, expert_dim, precision=precision)
            for _ in range(self.n_experts)
        ])
        shared = cfg.get("shared_expert")
        self.shared_expert = None
        if isinstance(shared, dict):
            self.shared_expert = ACSwiGLUFFN(
                d_model,
                int(shared["ffn_dim"]),
                precision=str(shared.get("precision", precision)),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        scores = torch.softmax(self.router(x).float(), dim=-1)
        top_scores, top_idx = torch.topk(scores, k=self.top_k, dim=-1)
        top_scores = top_scores.to(dtype=x.dtype)
        flat_x = x.reshape(-1, x.shape[-1])
        flat_scores = top_scores.reshape(-1, self.top_k)
        flat_idx = top_idx.reshape(-1, self.top_k)
        flat_out = torch.zeros_like(flat_x)
        for slot in range(self.top_k):
            slot_idx = flat_idx[:, slot]
            slot_weight = flat_scores[:, slot].unsqueeze(-1)
            for expert_id, expert in enumerate(self.experts):
                mask = slot_idx == expert_id
                if mask.any():
                    flat_out[mask] += expert(flat_x[mask]) * slot_weight[mask]
        out = flat_out.reshape_as(x)
        if self.shared_expert is not None:
            out = out + self.shared_expert(x)
        return out


class ACAttention(nn.Module):
    def __init__(
        self,
        d_model: int,
        cfg: Dict[str, Any],
        *,
        rope_base: float = 500000.0,
        component_overrides: Optional[Dict[str, Any]] = None,
    ):
        super().__init__()
        self.cfg = cfg
        self.type = str(cfg.get("type", "full")).lower()
        self.n_heads = int(cfg["n_heads"])
        self.n_kv_heads = int(cfg.get("n_kv_heads", self.n_heads))
        self.d_head = int(cfg["d_head"])
        self.rope = bool(cfg.get("rope", True))
        self.rope_base = float(rope_base)
        precision = (cfg.get("precision") or {}).get("v", "bf16")
        dtype = _precision_to_dtype(precision)
        overrides = component_overrides or {}
        self.external_attention = overrides.get(f"attention:{self.type}")

        if self.type == "mla":
            c_q = int(cfg.get("q_latent_dim") or cfg.get("kv_latent_dim") or d_model)
            c_kv = int(cfg.get("kv_latent_dim") or d_model)
            self.q_down = nn.Linear(d_model, c_q, bias=False, dtype=dtype)
            self.q_up = nn.Linear(c_q, self.n_heads * self.d_head, bias=False, dtype=dtype)
            self.kv_down = nn.Linear(d_model, c_kv, bias=False, dtype=dtype)
            self.k_up = nn.Linear(c_kv, self.n_kv_heads * self.d_head, bias=False, dtype=dtype)
            self.v_up = nn.Linear(c_kv, self.n_kv_heads * self.d_head, bias=False, dtype=dtype)
        else:
            self.q_proj = nn.Linear(d_model, self.n_heads * self.d_head, bias=False, dtype=dtype)
            self.k_proj = nn.Linear(d_model, self.n_kv_heads * self.d_head, bias=False, dtype=dtype)
            self.v_proj = nn.Linear(d_model, self.n_kv_heads * self.d_head, bias=False, dtype=dtype)
        self.o_proj = nn.Linear(self.n_heads * self.d_head, d_model, bias=False, dtype=dtype)
        self.flash_attn_func = _optional_attr("flash_attn", "flash_attn_func")

    def _project_qkv(self, x: torch.Tensor):
        bsz, seq, _ = x.shape
        if self.type == "mla":
            q = self.q_up(self.q_down(x)).view(bsz, seq, self.n_heads, self.d_head)
            latent = self.kv_down(x)
            k = self.k_up(latent).view(bsz, seq, self.n_kv_heads, self.d_head)
            v = self.v_up(latent).view(bsz, seq, self.n_kv_heads, self.d_head)
        else:
            q = self.q_proj(x).view(bsz, seq, self.n_heads, self.d_head)
            k = self.k_proj(x).view(bsz, seq, self.n_kv_heads, self.d_head)
            v = self.v_proj(x).view(bsz, seq, self.n_kv_heads, self.d_head)
        return q, k, v

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.external_attention is not None:
            return self.external_attention(x, self.cfg)
        q, k, v = self._project_qkv(x)
        if self.rope:
            q = _apply_rope(q.transpose(1, 2), self.rope_base).transpose(1, 2)
            k = _apply_rope(k.transpose(1, 2), self.rope_base).transpose(1, 2)
        if self.flash_attn_func is not None and q.is_cuda:
            try:
                out = self.flash_attn_func(q, k, v, causal=True)
                return self.o_proj(out.reshape(x.shape[0], x.shape[1], -1))
            except Exception:
                pass
        q = q.transpose(1, 2)
        k = k.transpose(1, 2)
        v = v.transpose(1, 2)
        if self.n_kv_heads != self.n_heads:
            if self.n_heads % self.n_kv_heads != 0:
                raise ValueError("n_heads must be divisible by n_kv_heads for GQA fallback")
            repeat = self.n_heads // self.n_kv_heads
            k = k.repeat_interleave(repeat, dim=1)
            v = v.repeat_interleave(repeat, dim=1)
        out = F.scaled_dot_product_attention(q, k, v, is_causal=True)
        out = out.transpose(1, 2).reshape(x.shape[0], x.shape[1], -1)
        return self.o_proj(out)


class ACStateMixer(nn.Module):
    def __init__(
        self,
        d_model: int,
        cfg: Dict[str, Any],
        *,
        component_overrides: Optional[Dict[str, Any]] = None,
    ):
        super().__init__()
        self.cfg = cfg
        self.state_type = str(cfg.get("type") or cfg.get("state_type") or "mamba2").lower()
        overrides = component_overrides or {}
        factory = overrides.get(f"state:{self.state_type}") or overrides.get("state")
        if factory is not None:
            self.impl = factory(d_model=d_model, config=cfg)
            return
        self.impl = self._build_external(d_model, cfg)

    def _build_external(self, d_model: int, cfg: Dict[str, Any]) -> nn.Module:
        # Prefer user overrides for serious training. These imports are best
        # effort because external package APIs move quickly.
        if self.state_type in {"mamba2", "mamba"}:
            cls = _optional_attr("mamba_ssm", "Mamba2") or _optional_attr("mamba_ssm", "Mamba")
            if cls is not None:
                return cls(d_model=d_model, d_state=int(cfg.get("d_state", 128)))
        fla_candidates = {
            "gla": ("fla.layers", "GLA"),
            "kda": ("fla.layers", "KDA"),
            "gated_delta": ("fla.layers", "GatedDeltaNet"),
            "gated_deltanet": ("fla.layers", "GatedDeltaNet"),
            "deltanet": ("fla.layers", "DeltaNet"),
            "rwkv7": ("fla.layers", "RWKV7Attention"),
            "linear_attention": ("fla.layers", "BasedLinearAttention"),
        }
        mod_attr = fla_candidates.get(self.state_type)
        if mod_attr is not None:
            cls = _optional_attr(*mod_attr)
            if cls is not None:
                return cls(d_model=d_model)
        raise ImportError(
            f"No external state mixer found for {self.state_type!r}. "
            "Install the relevant package or pass component_overrides="
            "{'state:<type>': factory}."
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.impl(x)


class ACBlock(nn.Module):
    def __init__(
        self,
        d_model: int,
        layer_spec: Dict[str, Any],
        *,
        rope_base: float,
        component_overrides: Optional[Dict[str, Any]] = None,
    ):
        super().__init__()
        norm_cfg = layer_spec.get("normalization") or {}
        self.norm1 = ACRMSNorm(d_model, eps=float(norm_cfg.get("eps", 1e-5)))
        self.norm2 = ACRMSNorm(d_model, eps=float(norm_cfg.get("eps", 1e-5)))
        if layer_spec.get("type") == "state_block":
            self.mixer = ACStateMixer(
                d_model,
                layer_spec.get("state") or {},
                component_overrides=component_overrides,
            )
        else:
            self.mixer = ACAttention(
                d_model,
                layer_spec["attention"],
                rope_base=rope_base,
                component_overrides=component_overrides,
            )
        ffn_cfg = layer_spec.get("ffn") or {}
        if ffn_cfg.get("type") == "moe":
            self.ffn = ACMoEFFN(d_model, ffn_cfg)
        else:
            self.ffn = ACSwiGLUFFN(
                d_model,
                int(ffn_cfg["ffn_dim"]),
                precision=str(ffn_cfg.get("precision", "bf16")),
            )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.mixer(self.norm1(x))
        x = x + self.ffn(self.norm2(x))
        return x


def _expand_layer_specs(architecture: Dict[str, Any]) -> List[Dict[str, Any]]:
    n_layers = int(architecture["n_layers"])
    specs: List[Optional[Dict[str, Any]]] = [None] * n_layers
    for group in architecture["layer_configs"]:
        for idx in group["layer_idx"]:
            specs[int(idx)] = group
    missing = [i for i, spec in enumerate(specs) if spec is None]
    if missing:
        raise ValueError(f"Config is missing layer specs for indices: {missing}")
    return [dict(spec) for spec in specs if spec is not None]


class __CLASS_NAME__(nn.Module):
    """PyTorch module generated from AC_CONFIG.

    Parameters
    ----------
    config:
        AC schema config. Defaults to the embedded AC_CONFIG.
    component_overrides:
        Optional adapter map for lab kernels. Examples:
        {"attention:nsa": callable, "state:gla": factory, "state:mamba2": factory}
    """

    def __init__(
        self,
        config: Optional[Dict[str, Any]] = None,
        *,
        component_overrides: Optional[Dict[str, Any]] = None,
    ):
        super().__init__()
        self.config = config or AC_CONFIG
        arch = self.config["architecture"]
        self.d_model = int(arch["d_model"])
        self.vocab_size = int(arch["vocab_size"])
        pos = arch.get("positional_encoding") or {}
        self.rope_base = float(pos.get("base", 500000))
        self.embed_tokens = nn.Embedding(self.vocab_size, self.d_model)
        self.layers = nn.ModuleList([
            ACBlock(
                self.d_model,
                spec,
                rope_base=self.rope_base,
                component_overrides=component_overrides,
            )
            for spec in _expand_layer_specs(arch)
        ])
        self.norm = ACRMSNorm(self.d_model)
        self.lm_head = nn.Linear(self.d_model, self.vocab_size, bias=False)
        if bool(arch.get("tied_embeddings", False)):
            self.lm_head.weight = self.embed_tokens.weight

    @classmethod
    def from_config(
        cls,
        config: Dict[str, Any],
        *,
        component_overrides: Optional[Dict[str, Any]] = None,
    ):
        return cls(config=config, component_overrides=component_overrides)

    def forward(
        self,
        input_ids: torch.Tensor,
        labels: Optional[torch.Tensor] = None,
        **_: Any,
    ) -> Dict[str, torch.Tensor]:
        x = self.embed_tokens(input_ids)
        for layer in self.layers:
            x = layer(x)
        x = self.norm(x)
        logits = self.lm_head(x)
        out: Dict[str, torch.Tensor] = {"logits": logits}
        if labels is not None:
            loss = F.cross_entropy(
                logits[:, :-1].contiguous().view(-1, logits.shape[-1]),
                labels[:, 1:].contiguous().view(-1),
            )
            out["loss"] = loss
        return out
'''
